In [5]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Rerim\OneDrive\Desktop(3)\rerisongit\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\Users\Rerim\OneDrive\Desktop(3)\rerisongit\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.8 MB 6.6 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.8 MB 5.9 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.8 MB 5.4 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.8 MB 5.3 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.8 MB 4.9 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.8 MB 4.5 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.8 MB 4.0 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.8 MB 4.0 MB/s eta 0:00:01
   ------------------------- -------------- 6.3/9.8 MB 3.5 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.8 MB 3.2 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.8 MB 3.2 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 2.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 2.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 2.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 2.8 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 2.1 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.8 MB 1.8 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.8 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.8 MB 1.6 MB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.6 MB/s  0:00:05
Downloading numpy-2.5.4-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.7 MB 2.3 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.7 MB 2.6 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.7 MB 2.7 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.7 MB 2.9 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.7 MB 2.6 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/12.7 MB 2.2 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.7 MB 2.2 MB/s eta 0:00:05
   --------- ------------------------------ 3.1/12.7 MB 1.8 MB/s eta 0:00:06
   ---------- ----------------------------- 3.4/12.7 MB 1.7 MB/s eta 0:00:06
   ------------ --------------------------- 3.9/12.7 MB 1.8 MB/s eta 0:00:05
   -------------- ------------------------- 4.5/12.7 MB 1.9 MB/s eta 0:00:05
   -------------- ------------------------- 4.7/12.7 MB 1.9 MB/s eta 0:00:05
   --------------- ------------------------ 5.0/12.7 MB 1.9 MB/s eta 0:00:05
   ---------------- ----------------------- 5.2/12.7 MB 1.8 MB/s eta 0:00:05
   ---------------- ----------------------- 5.2/12.7 MB 1.8 MB/s eta 0:00:05
   ----------------- ---------------------- 5.5/12.7 MB 1.6 MB/s eta 0:00:05
   ------------------ --------------------- 6.0/12.7 MB 1.6 MB/s eta 0:00:05
   -------------------- ------------------- 6.6/12.7 MB 1.7 MB/s eta 0:00:04
   ---------------------- ----------------- 7.1/12.7 MB 1.7 MB/s eta 0:00:04
   ----------------------- ---------------- 7.6/12.7 MB 1.8 MB/s eta 0:00:03
   ------------------------- -------------- 8.1/12.7 MB 1.8 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.7 MB 1.8 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.7 MB 1.8 MB/s eta 0:00:03
   ----------------------------- ---------- 9.4/12.7 MB 1.9 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.7 MB 1.9 MB/s eta 0:00:02
   ----------------------------------- ---- 11.3/12.7 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.7 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 2.2 MB/s  0:00:05
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.4 pandas-3.0.6 tzdata-2026.5
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/Projetar-Solucoes/materiais-trilha/main/semana-04/solicitacoes_semana4.csv")
display (df)

,protocolo,data_abertura,solicitante,setor,categoria,assunto,prioridade,status,data_fechamento,avaliacao,unidade
0,2026-0173,2026-09-26,Bruno Nunes,Atendimento,Suporte de TI,Impressora sem conexão,Média,Aberta,NaN,NaN,Parambu
1,2026-0053,2026-08-31,Marta Dias,Comercial,ACESSO,Acesso ao sistema de ponto,Média,Concluída,2026-09-03,4.0,Parambu
2,2026-0238,2026-09-06,Nilo Barros,Operações,dúvida,Horário do plantão,Baixa,Concluída,2026-09-06,3.0,Solonópole
3,2026-0103,2026-08-31,Bruno Barros,RH,Suporte TI,Impressora sem conexão,Alta,Concluída,2026-09-15,4.0,Parambu
4,2026-0013,18/08/2026,Sérgio Alves,RH,Infraestrutura,Cadeira quebrada,Alta,Aberta,NaN,NaN,Parambu
...,...,...,...,...,...,...,...,...,...,...,...
241,2026-0204,2026-08-06,Ana Moura,Diretoria,Infraestrutura,Tomada queimada,Média,Concluída,2026-08-07,NaN,Parambu
242,2026-0235,2026-08-17,Lucas Dias,Comercial,Duvida,Horário do plantão,Alta,Cancelada,NaN,NaN,Solonópole
243,2026-0228,2026-08-27,Rita Freitas,Comercial,dúvida,Uso da plataforma,Urgente,Concluída,2026-08-28,3.0,Solonópole
244,2026-0174,2026-08-29,Bruno Costa,Financeiro,acesso,Senha bloqueada,Alta,Aberta,NaN,NaN,Parambu
245,2026-0077,21/09/2026,Sérgio Gomes,Financeiro,acesso,Senha bloqueada,Média,Concluída,2026-09-23,3.0,Parambu

In [7]:
df = df.drop_duplicates()
display(df)

,protocolo,data_abertura,solicitante,setor,categoria,assunto,prioridade,status,data_fechamento,avaliacao,unidade
0,2026-0173,2026-09-26,Bruno Nunes,Atendimento,Suporte de TI,Impressora sem conexão,Média,Aberta,NaN,NaN,Parambu
1,2026-0053,2026-08-31,Marta Dias,Comercial,ACESSO,Acesso ao sistema de ponto,Média,Concluída,2026-09-03,4.0,Parambu
2,2026-0238,2026-09-06,Nilo Barros,Operações,dúvida,Horário do plantão,Baixa,Concluída,2026-09-06,3.0,Solonópole
3,2026-0103,2026-08-31,Bruno Barros,RH,Suporte TI,Impressora sem conexão,Alta,Concluída,2026-09-15,4.0,Parambu
4,2026-0013,18/08/2026,Sérgio Alves,RH,Infraestrutura,Cadeira quebrada,Alta,Aberta,NaN,NaN,Parambu
...,...,...,...,...,...,...,...,...,...,...,...
241,2026-0204,2026-08-06,Ana Moura,Diretoria,Infraestrutura,Tomada queimada,Média,Concluída,2026-08-07,NaN,Parambu
242,2026-0235,2026-08-17,Lucas Dias,Comercial,Duvida,Horário do plantão,Alta,Cancelada,NaN,NaN,Solonópole
243,2026-0228,2026-08-27,Rita Freitas,Comercial,dúvida,Uso da plataforma,Urgente,Concluída,2026-08-28,3.0,Solonópole
244,2026-0174,2026-08-29,Bruno Costa,Financeiro,acesso,Senha bloqueada,Alta,Aberta,NaN,NaN,Parambu
245,2026-0077,21/09/2026,Sérgio Gomes,Financeiro,acesso,Senha bloqueada,Média,Concluída,2026-09-23,3.0,Parambu

In [10]:

df_copy = df.copy()

df_copy["categoria"] = df_copy["categoria"].str.strip().str.lower()

padrao = {
    "suporte ti": "Suporte TI",
    "suporte de ti": "Suporte TI",
    "acesso": "Acesso",
    "financeiro": "Financeiro",
    "infraestrutura": "Infraestrutura",
    "infra": "Infraestrutura",
    "dúvida": "Dúvida",
    "duvida": "Dúvida",
}

df_copy["categoria"] = df_copy["categoria"].map(padrao)

display(df_copy["categoria"].value_counts())

categoria
Dúvida            52
Infraestrutura    51
Acesso            48
Financeiro        46
Suporte TI        43
Name: count, dtype: int64

In [11]:
import pandas as pd

df_copy["status"] = df_copy["status"].str.capitalize()

df_copy["avaliacao"] = df_copy["avaliacao"].replace(7, float("nan"))

media_avaliacao = df_copy.groupby("categoria")["avaliacao"].mean()

display(media_avaliacao)

display(df_copy["categoria"].value_counts())

categoria
Acesso            3.952381
Dúvida            3.800000
Financeiro        4.038462
Infraestrutura    3.291667
Suporte TI        3.791667
Name: avaliacao, dtype: float64

categoria
Dúvida            52
Infraestrutura    51
Acesso            48
Financeiro        46
Suporte TI        43
Name: count, dtype: int64